# Generated by Django 2.2.5 on 2021-10-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guests',
            new_name='guest',
        ),
    ]
